### ISSUE TITLE
Unused DX9

### ISSUE THREAD

**Issue by leadedge** [robtherich/SpoutJitter#2]
Hi Rob,

A problem has been reported recently and it appears that Resolume reads an unused registry key value "DX9" after the Max Spout external sets it true. This does not affect the function of the external, but Resolume Spout sending fails. The DX9 flag is not required any more, so removing it would be best in the long run.

jit.gl.spoutsender lines 548,549,500. Remove the else that sets DX9 true. With format set to zero, the default DXGI_FORMAT_B8G8R8A8_UNORM is used.

**Comment by robtherich** [comment]
thanks for filing, will check it out!

**Comment by robtherich** [comment]
this change has been committed and the externals updated and pushed to the Package Manager as Spout package version 2.0.75

**Comment by leadedge** [comment]
Thanks Rob. I have advised on the Spout discourse group.
